const promocionesCSV = `Icono,Titulo,Subtitulo,Condicion,Validez,HoraInicio,HoraFin,Reloj
sports_bar,METE TU POMO!!!, , , , 12,24,OFF
sports_bar,2X1 EN CUBOS,XX TECATE E INDIO,SABADO,VÁLIDO HASTA LAS 12:00 AM,12,24,ON
diamond,2 X $199 EN LITROS , ,SABADO,VÁLIDO HASTA LAS 11:00 PM,12,24,ON
local_bar,$699 BOTELLAS NACIONALES,INCLUYE MEZCLADORES,SABADO,VÁLIDO HASTA LAS 12:00 PM,12,24,ON`;
