const promocionesCSV = `Icono,Titulo,Subtitulo,Condicion,Validez,HoraInicio,HoraFin,Reloj
local_bar,$699 BOTELLAS BASICAS,INCLUYE MEZCLADORES,SABADO,VÁLIDO HASTA LAS 11:00 PM,2,24,ON
diamond,$1799 BOTELLAS PREMIUM ,INCLUYE MEZCLADORES,SABADO,VÁLIDO HASTA LAS 11:00 PM,2,24,ON
sports_bar,2X1 EN CUBOS,XX TECATE E INDIO,TODOS LOS DÍAS,VÁLIDO HASTA LAS 12:00 AM,24,24,OFF`;
